#!/bin/bash
#
# Samplicator control
# 
# commands
# 
# start : start the samplicate process(es) defined in the configfile
# satus : show the status of the process(es) defined in the configfile
# stop : kill the process(es)
#
# 
# . /etc/init.d/functions
config="launch-example.cfg"

samplicator="/usr/bin/samplicate"

start () {
	echo -n $"Starting samplicator daemons: " 
	if [ -f $config ]; then
		while IFS="," read address port debug pid_file config_file
		do 
		  echo "loop"
		  if [ "$address" == "address" ]; then continue ; fi 
		  echo "$samplicator -s $address -p $port -d $debug -m $pid_file -c $config_file -S -f"
		  echo "Lanzamos samplicate con opciones address= $address port= $port debug=$debug pid_file= $pid_file config=$config_file"
		done < $config	
		RETVAL=$?
    		echo
   		[ $RETVAL -eq 0 ] && touch /var/lock/subsys/rhnsd
	else 
		echo "Error $config don't exists" 
		exit -1 
	fi

}

stop () {
	echo "Stopping samplicate daemons"
	if [ -f $config ]; then
		while IFS="," read address port debug pid_file config_file
		do 
		  if [ "$address" == "address" ]; then continue ; fi 
		  killproc -p $pid_file samplicator 
		done < $config	
		RETVAL=$?
    		echo
    		[ $RETVAL -eq 0 ] && touch /var/lock/subsys/rhnsd
	else 
		echo "Error $config don't exists" 
		exit -1 
	fi


 
}

status () {
	if [ -f $config ]; then
		while IFS="," read address port debug pid_file config_file
		do 
		 status -p $pid_file rhnsd
		done < $config	
		 RETVAL=$?
	else 
		echo "Error $config don't exists" 
		exit -1 
	fi

} 

case "$1" in 
  start)
	start;
  ;;

  stop)
	stop;
  ;;
  restart)
	stop;
	start;
  ;;
  status)
	status;
        ;;
   *)
       	echo $"Usage: $0 {start|stop|status|restart}" 
       exit 1;
esac

exit $?

